### ISSUE TITLE
just js would be nice

### ISSUE THREAD

**Issue by tj** [ravelsoft/node-jinjs#16] opened 2011-09-07 15:56 UTC
I really want to provide a solid django-inspired template engine for the Express users, and this certainly looks like a good start. _however_ that weird language you're using is going to be a big barrier for contribution. I definitely recommend just writing js in js so people like myself who actually know the language can help tune/fix things

**Comment by ceymard** [comment] 2011-09-08 13:43
I agree...

However, I'm not really fond of changing it to JS.

JS is at times cumbersome to use, and coco abstracts lots of stuff elegantly (callbacks are a breeze). And besides, that language is still very close to javascript (and compiles down to it too ; the code in npm is actually javascript - and it's readable), and actually deserves to be more known.

Its big brother, Coffeescript, is pretty widely used. The main problem with coco is that it lacks a good documentation - I offered myself to write one, and will definitively do so in the future.

To clarify my situation on the matter ; I entirely agree with you. But I really have issues with JS and really don't like developping in it. This could change on this particular project, but while there are not many people interested in contributing, it will stay that way for now.

**Comment by razorg** [comment] 2011-09-16 13:38
I understand you might have issues with pure JS, but i think it would be worth to overtake them for the shake of the project. It is very solid, but i find myself lost in the abyss when i try to read the code. I can't say if coco is better than pure js, but since the vast majority of the community is using the latter, then it would make more sense if you could try switching to it, than the whole community start learning coco.

And the fact that not many people are interested in contributing to the project, might be caused by the frustration caused by coco, at least to me. @visionmedia looks interested into contributing so that is a big start!

What you have made is worth a lot, lets get into tuning it!

**Comment by ceymard** [comment] 2011-09-16 14:00
Well, why not.

The only thing is ; coco would generate the JS files, but they are not extremely easy to read (as in, I wouldn't code that way in JS). I think this is a big change, which is going to take quite some time to tune it visually.

Which coding style to adopt ? Which library to use to palliate for JS's awful semantics ? underscore ?

Also, and this something that I'm not fond of, what to do about JS's lack of multiline strings, let alone the lack of string interpolation ? 

I sure don't want to convert 

``` coffeescript
"#{@cur opts}var names = ['#{imports.join "', '"}'];
 #{@cur opts}for (var i = 0; i < names.length; i++) {
     #{@ind opts}__ctx__[names[i]] = __new_ctx[names[i]];
#{@ded opts}}"
```

into

``` javascript
[ this.cur(opts) + "var names = ["' + imports.join('\', \'') + '"];",
  this.cur(opts) + "for var(i = 0; i < names.length; i++) {",
  this.ind(opts) + "__ctx__[names[i]] = __new_ctx[names[i]];",
  this.ded(opts) + "" ].join("\n");
```

As I have seen elsewhere, which is the most acceptable solution for readability, yet it is problematic (still ugly, and join() steals some precious CPU time for _no reason at all_)

I have read and participated in the whole troll of CS vs JS in the node mailing list, and I agree it divises the community. But frankly, I really have a problem with JS. I don't think I would be this eager to contribute to it other than making small fixes here and there if it were in JS.

In fact, I took coco because I found it while in the process of actually creating a language of my own (didn't know it existed at the time), since it was so painful to code in JS.

So yeah, let's change it. Let's choose a coding style, and a core library. I want more this project to take off than having it my way, but frankly, this is killing me.

**Comment by tj** [comment] 2011-09-16 15:03
js is a fine language, the issues that it does have, have nothing to do with syntax, and you very rarely need libraries like underscore (unless working on the client-side). String interpolation, is retarded no offence, it blows my mind that people prefer `"foo #{bar} baz"` over `"foo " + bar + " baz"`, if you squish those down you're barely even saving chars. Other than it looks like you're doing a good job, I had a half-finished implementation but I would much rather help out with this one if it's going the right direction

**Comment by ceymard** [comment] 2011-09-16 15:49
I prefer `"#filename.#ext"` over `filename + "." + ext;`

Call me retarded if you will, but interpolation appears to me a lot more elegant, as it is less noisy.

About the syntax issue, yes, there is an impact. Coco/CS is not just about silly sugar. Consider the following ;

Javascript

``` javascript
for (i = 0; i < container.length; i++) {
    obj = container[i]; // or write container[i] all the time.
    // do stuff with obj
}
```

nicer way :

```
_.forEach(container, function(obj, i) {
   // do stuff with obj
});
```

And at last ;

``` coffeescript
for obj of container
   # do stuff with obj
```

I find there is a great deal of difference. Also, for copying objects, you would need `_.extend({}, obj)` or something of the like, coco has `^obj` for cloning or `{} <<< obj` for importing obj's properties into an empty one. Doing this in pure JS is in fact atrocious :

```
var new = {};
for (x in obj) {
    if (obj.hasOwnProperty(x)) { // also note that this isn't valid everywhere, coco adds a series of shims for that
         new[x] = obj[x];
    }
}
```

So. Yes, it's about syntax. JS has a lot of deficiencies that are corrected through smart libraries (underscore, parts of jquery, etc...). Choosing a good one will be important.

What I find annoying about JS is precisely that I have to use all those "shims" that not only allow us to express stuff in a more robust way, it also ensures it works across all its supported platforms.

Using coco or Coffeescript is akin using these smart libraries, except they're actually expressed in their own syntax, syntaxes that are shared by a number of other programming languages.

Anyways. I'm trolling a little, and it's not the objective.

I agree about a rewrite, but I'll need help. I also want to agree about which things we'll use and what coding style will be employed.

Also, I will not refuse help for that ; it's a big task, and more, an unpleasant one for me. You can always grab coco (`npm -g install coco`) and execute it on a .co file to get it's javascript traduction and correct it from there (to make it more readable) : `coco -bp file.co`.

We also could use some kind of beautifier, I don't know. I'm just looking for suggestions.

**Comment by razorg** [comment] 2011-09-16 15:53
Other than Underscore, there is https://github.com/ollym/toolkit also.
If you decide on a lib, i can help with the porting. I dont have a lot 
of experience on the two, so cant have a say.

**Comment by tj** [comment] 2011-09-16 16:05
there's no need for underscore on the server, and in the case of targeting the client as well if we're compiling to a javascript Function, then there's also no need for underscore (or similar) as you can toString() the function and avoid the rest of the library (jade etc do this)

**Comment by ceymard** [comment] 2011-09-16 23:31
@razorg : I have to say I like toolkit better. Let's go for this one.

**Comment by ceymard** [comment] 2011-09-18 16:13
I'm just going to delay the port to JS a little (sorry !) : I would like to have Jinjs get to feature near-completion before making the change ; so far, I'm the one with most experience with the project, and I can advance fairly fast.

The changes to JS is a very big, non-trivial task, and I would like to do it when the project is "a little" more stable, mainly because I think I will contribute less towards its advancement when it's in js (not that I will desert the project, _far_ from it, but I think I will mostly try to coordinate the people who want to participate and fix bugs).

There is a list of open issues ; which do you think must go in asap and which could be delayed to after the transition ? Which features that are not implemented yet and not listed either do you want in ?

I'll try to go as fast as possible.

**Comment by razorg** [comment] 2011-09-18 19:03
Issues [#4](https://github.com/ravelsoft/node-jinjs/issues/4) and [#5](https://github.com/ravelsoft/node-jinjs/issues/5) would be interesting features. And the escaping policy is more important i think.

I am curious to try out converting coco to js. Ill fork and tell you how it goes.

**Comment by ceymard** [comment] 2011-09-18 19:13
Alright,

I just hope you won't suffer too much if I make changes.

**Comment by ceymard** [comment] 2011-09-28 15:42
Closing for now, relaunching transition when at feature complete (tests + auto escaping + trans at least)

**Closed as completed by ceymard** 2011-09-28 15:42 UTC

**Comment by tj** [comment] 2011-09-28 16:31
no worries I found another django-ish template engine written with js

**Comment by ceymard** [comment] 2011-09-28 18:15
are you talking about swig ? just discovered it a few days ago. seems interesting.

**Comment by tj** [comment] 2011-09-28 18:57
yeah i think that's the one

**Comment by ghost** [comment] 2012-02-14 03:27
swig is not mature, some useful features like nested block, are not supported. That's disappointing. So I just turn to this project...

I prefer Jinja to Twig.

**Comment by tj** [comment] 2012-02-14 03:41
@jockyang at least it's written in js... not some language no one cares about, that's pretty important to me if I want to support/contribute to a project

**Comment by ceymard** [comment] 2012-03-06 23:02
Yeah he's right.

I'll rewrite it in JS when I have the time.
